name: rdf_core
description: A type-safe, modular Dart library for modeling, parsing, and serializing RDF data.
version: 0.5.2-dev
homepage: https://kkalass.github.io/rdf_core/
repository: https://github.com/kkalass/rdf_core
issue_tracker: https://github.com/kkalass/rdf_core/issues
documentation: https://kkalass.github.io/rdf_core/
topics:
  - rdf
  - linked-data
  - semantic-web
  - graph
  - serialization
readme: README.md
changelog: CHANGELOG.md
license: LICENSE
maintainers:
  - "Klas Kala√ü <habbatical@gmail.com>"
environment:
  sdk: ^3.7.0
dependencies:
  logging: ^1.2.0
  http: ^1.1.0
dev_dependencies:
  test: ^1.21.0
  yaml: ^3.1.2
  path: ^1.8.0
  build: ^2.4.1
  build_config: ^1.1.1
  build_runner: ^2.4.6
  source_gen: ^1.4.0
